name: Release Build

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            is_draft:
                description: 'Create a draft release?'
                required: false
                default: 'true'
                type: choice
                options:
                    - 'true'
                    - 'false'
permissions:
    contents: write
jobs:
    build:
        name: Build for ${{ matrix.system }}
        runs-on: ${{ matrix.runner }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    -   system: x86_64-linux
                        runner: ubuntu-latest
                    -   system: aarch64-linux
                        runner: ubuntu-latest
                    -   system: x86_64-windows
                        runner: windows-latest
                    -   system: aarch64-macos
                        runner: macos-latest
                    -   system: x86_64-macos
                        runner: macos-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up Rust
                uses: actions-rust-lang/setup-rust-toolchain@v1

            -   name: Build release binary
                run: cargo build --release

            -   name: Rename binary
                shell: bash
                run: |
                    mkdir -p dist
                    case "${{ matrix.system }}" in
                      *windows*) cp target/release/char-cloud.exe dist/char-cloud-${{ matrix.system }}.exe ;;
                      *)         cp target/release/char-cloud dist/char-cloud-${{ matrix.system }} ;;
                    esac

            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: char-cloud-${{ matrix.system }}
                    path: dist/**

    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')


        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    path: artifacts

            -   name: Generate checksums
                shell: bash
                run: |
                    cd artifacts
                    find . -type f ! -name '*.sha256' -exec sha256sum {} \; | while read -r hash path; do
                    echo "$hash  $path" > "${path}.sha256"
                    done
            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v1
                with:
                    files: artifacts/**/*
                    draft: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.is_draft == 'true' || true }}
                    generate_release_notes: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}