name: Release Build

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 检出代码
            -   name: Checkout repository
                uses: actions/checkout@v2

            # 缓存 Rust 编译工具链和依赖
            -   uses: actions/cache@v3
                with:
                    path: |
                        ~/.cargo/registry
                        ~/.cargo/git
                    key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-cargo-

            # 安装 Nix
            -   name: Install Nix
                uses: cachix/install-nix-action@v22
                with:
                    nix_version: 2.14.0 # 或指定您需要的版本

            # 使用 Nix 构建项目
            -   name: Build using Nix
                run: nix-build

            # 上传构建后的二进制文件作为 Release 产物
            -   name: Upload Release binary
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./result/bin/char-cloud # 替换为实际路径
                    asset_name: my_project-${{ github.ref_name }}-${{ runner.os }}.tar.gz
                    asset_content_type: application/gzip

    # 验证构建产物（可选）
    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install Nix
                uses: cachix/install-nix-action@v22

            -   name: Build and Run Tests
                run: |
                    nix-build
                    ./result/bin/char-cloud --version