name: Release Build

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.system }}
        runs-on: ${{ matrix.runner }}
        strategy:
            matrix:
                include:
                    -   system: x86_64-linux
                        runner: ubuntu-latest
                    -   system: x86_64-windows
                        runner: windows-latest
                    -   system: aarch64-darwin
                        runner: macos-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Install Nix
                uses: DeterminateSystems/nix-installer-action@main

            -   name: Set up Nix cache
                uses: DeterminateSystems/magic-nix-cache-action@main

            -   name: Build ${{ matrix.system }}
                run: nix build .#default

            -   name: Collect artifacts
                run: |
                    mkdir -p dist
                    cp -r result/* dist/
                    cp README.md LICENSE dist/ || true

            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: build-${{ matrix.system }}
                    path: dist/**