name: Release Build

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.system }}
        runs-on: ${{ matrix.runner }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    -   system: x86_64-linux
                        runner: ubuntu-latest
                    -   system: aarch64-linux
                        runner: ubuntu-latest
                    -   system: x86_64-windows
                        runner: windows-latest
                    -   system: aarch64-macos
                        runner: macos-latest
                    -   system: x86_64-macos
                        runner: macos-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up Rust
                uses: actions-rust-lang/setup-rust-toolchain@v1

            -   name: Build release binary
                run: cargo build --release

            -   name: Collect artifacts
                shell: bash
                run: |
                    mkdir -p dist
                    cp target/release/char-cloud* dist/
                    cp README.md LICENSE dist/ || true

            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: build-${{ matrix.system }}
                    path: dist/**

    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')

        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    path: artifacts

            -   name: Generate checksums
                shell: bash
                run: |
                    cd artifacts
                    for file in */*; do
                        sha256sum "$file" > "${file}.sha256"
                    done

            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v1
                with:
                    files: artifacts/**/*
                    draft: false
                    generate_release_notes: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}